apiVersion: networking.k8s.io/v1
kind: Ingress
metadata
  name: {{ include "helm.fullname" . }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{ toYaml . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "helm.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
                  